name:  APK 打包

on: workflow_dispatch
env:
  QL_URL: "${{ secrets.QL_URL }}"
  QL_CLIENT_ID: "${{ secrets.QL_CLIENT_ID }}"
  QL_CLIENT_SECRET: "${{ secrets.QL_CLIENT_SECRET }}"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - run: cd app/build/outputs/apk/release && mv *.apk qinglong-jd.apk


    - name: sign apk
      id: sign_app
      uses: upup-company/apksigner-android@v1
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: "MIIJwAIBAzCCCWoGCSqGSIb3DQEHAaCCCVsEgglXMIIJUzCCBaoGCSqGSIb3DQEH
AaCCBZsEggWXMIIFkzCCBY8GCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcN
AQUNMFkwOAYJKoZIhvcNAQUMMCsEFKlI3rH07T3J6aNCnD9OXob6XwkqAgInEAIB
IDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQJx5dI5cVbyqUixQWFuQ/nwSC
BNCJVpXEMv56WhhZ+LxtqE5rCFrPDqXzliYoGsuP5TX+SMTX1M6mli/ZlOhr22Nr
TqxonT2Z7/JcTWIZXMNExA2sLWVYjRgEQn6KH5YfCfPRy09PkEPdl5aq9F5IUZ9I
/0FeqkhAvMaYTAoMNTTHcszfdcx2MKuE3tQ8PLuNmZY/bD6jk69uBnNeYJ8Nnywk
Zb1g3pUO7mZCK2ftp2TKM8KfLt7oL/PODLYPaZMaEtA5mPy1S5bBQPU3qZC9GcTx
npH3OBwXwaEZYVIGzdbITdDQGgnlWr1Rb6v71yYPe3JIjALtenpvUYzAX28YcB6z
G9npclM00Rv/N6k8gNm5GYA70TIOFBaq/XHMcHip4ljykPe+xVlE1QEPByyQLG59
YqE/lMpejySQvDB6v5qnlaZlD6VSDWKV3w++OozcJ4j9sfpkd5mK2nOB8aBZDZ22
z35fxYk1DM8qPr0La1YRNHG64qMJagXhw7GrSquJzNUy/o8GnCBe8Sb9OJhcw3+6
Hge79jkw3hY/a2c18soiyy7JWLqpu3u6ZFkKnMZEU/zoXuFMQ8gipGpic1bNIFSz
wy84gOkr8nmMBeL7YHrogewT2eehSHqN5SzSd31Tfy/wXUNVGPm5tpUexeYdXnQz
+ezNNErbjKy5rkADNhXU75HbvWWA5zfcA8KNR72MqRhC2f1b8AxpONYTyp0H8d2t
hL8AlEZ2KLa11s7fiGT8RhTKBfsCYQ3bTOg9IGGF4LAmVnEwjqrl8qEv+Gq3nisS
W0OkH8/qP2kbGMmztcaKc6VdqQrDbarZ0Oz5dJFgQFQZUKa5ZvxHfx3C7eXrhxlp
rWxUjeBmatRhr9zpnX2sx0vWNJVgC3mi4355GRMg9w919NX5LmahnVtDjlKGaunl
5TkETzzq3M8N4313uSseuZz7JF47stFgG8BN+ptgbS7mz9cS5IkhKoHn59783VtP
nphXHdoHFDpeaC0/CUYU8YBYdk4G2yav5lcSQd/oFrdSljS5tzs7wdz84nAJRHKs
pL/mk8E03nPs9TUDhbiEiuvXuywj1CCyNphzgoqUM1u4eq/ikdT55Sbnm0stdK3k
thtbmW9cg/yf/z75qIkuHqmyX1zpfaF61hoCVnWxEs2tCayJcosy9vSICdL4m69M
T4ei/nsvEI5aSO5XcpYxdj7ZbgVpSeQBaahXvGPCRi6Q2xJwyVU4Vsy4sC223pSs
ZBT0xSbnk058OkGSrZCCr+RL6LXlDB6eHf1bOY+SaurRhpihpt32/ACBWA1Ov4uF
88PIJvs7X2raZxqk2tNw/BuQK4jt4WZ/H6XGb0mJVhkz0PVYVzo/spuSJoV97e/0
nsEpY+Y76GQftMeQFbLf/eTVq0zILLN66x8EpgcBho/FuVdqQQNfh1Wms5/kPfWC
HUevKea8AB0klBgfQsy6Wft3EMNT12xHOK0z9ZXT7Qt8r/6wqzUmm3goQXYfEl72
dIMPnWZw4ZOUCkwo7WqVQjwyKY8Odj91/2fBJqQ1ZlIV5J1GkI5Ei9F5x0443oem
h8nyWVrEdamqtyvn6hlb6oy9lkp7x7tTVhpkyjt66i6eMKDMV9n8uJUAtpkeTaqr
0sn+0838ojmKf4dMzvCY5z6i2KpJUtiEPLgdsXwENgcEVjE8MBcGCSqGSIb3DQEJ
FDEKHggAawBlAHkAMDAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNzAwMTQ5Nzg4MDYz
MIIDoQYJKoZIhvcNAQcGoIIDkjCCA44CAQAwggOHBgkqhkiG9w0BBwEwZgYJKoZI
hvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFGI/N5b1kBO2n4EBYirOmiKa0HJDAgIn
EAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ5adnpbIfJEExJ3cnKYAr
oICCAxBJj7zbhh5acmz2LQRk6p4HAMnu57voAOcEUlbWU0mD5giqu4ZTGX79z06U
RzY3lpa3m6lOEFeU2xCS4GmsVKuhDb5N9oRZeL51paB9nWKZlcNYMOVAaLCInfBb
Epff7S8OGG3qEkpQORafceEw8Ifmpm1dI/1L6e3dxOm2aZpyy/XA/xYri0qLF5FB
LZsdA9BeAG3PKp3wHe4zEIWbabfGlcM2lBeVTAc2tADyWuFdtUwbl+N3N8rHUifl
d/0BeIDuQXqWBFwkOFKi48sWEtyE1y/+BhxJcJ834FBzNnSf1qSzeLr7i35gaUD0
VqhIY90I5CgnMuCQFEuluKG4zuQlBP+cB7baN64q5FleBoATBsaNbCw9z3QIJg76
bju3ARpw6YpEWYfCMpTHV/LNalFlNVYcSrErXVIZxl+kbFPg4hlgEsSiQy2myrLT
mieuzLGb/FwkPtnvOVgfvwayj6ILpPsgpltz65XS1wv71ykjWFC27LdcxkuPwPy0
nsaMvvuLx2E8iLeTi3r0wpTMzuitqk9+5aWlgjClHVxbOTdx/7ooSDoExQyAbCnf
SShKPY4LaPp9YGBBcv4bzp7sKBgBrANjlqqzMVZKkqWEHL0JxRdGP5CxzHirSdy/
4jHefL9zn67meFhgGueXAL8iMUpL2gbqpN1zxbxVQEiHUZW2SvCZllt8y9qCSpuL
bwNej+ghfSX7mddrVklNHZntLMXB5Ls4SAAA6nJPTvLLLB2lySsfx11fp6evUQYq
r2LsHDH0ccc29RhtaaHR74xMEDFjzGPOa+zerblpBD95F+REAuZ4ZeJJ2NXcX/4b
P7eUCxeCKMGrD/Mbvxl7b8PNinkRbcOHWDJnakHhq8w8dhm9LqwWVPzx0f3F5VNG
dJq7cHstRzs5iNpgtFvIFJxvDx5Y6ZkJNg/stkfQXyP34dm+QTbxcy46owg39Bsd
X3pJ211PAxEBwf+s3PTbnL3oMXSybAh9ooPscC3Bz9hjOoM3PTFQfi2lxvXHst0E
q79ZKWMsxtbkBAjaiOqlptom8aTSME0wMTANBglghkgBZQMEAgEFAAQgrnCRLPUj
dweWd2xJoNFsA+H6hKI3GM7jGO7DBLOzH4AEFBcVg7/EKE1gzYLfZHSi75PQrRem
AgInEA=="
        alias: key0
        keyStorePassword: 123123
        keyPassword: 123123
      env:
        BUILD_TOOLS_VERSION: "33.0.3"
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{github.run_id}}
        title: "apk打包"
        prerelease: false
        files: |
            ${{steps.sign_app.outputs.signedReleaseFile}}